In [1]:
df = pandas.read_csv("ipums_extracted.csv")

NameError: name 'pandas' is not defined

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("ipums_extracted.csv")

In [4]:
import numpy as np

In [5]:
df

,Unnamed: 0,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,ASECWTH,STATEFIP,PERNUM,...,OCC50LY,INDLY,OCC90LY,IND90LY,FULLPART,FIRMSIZE,INCTOT,INCWAGE,EDATT,EDATTLY
0,1,1988,1,1,NaN,1.987100e+13,NaN,NaN,6,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1988,1,1,NaN,1.987100e+13,NaN,NaN,6,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1988,1,1,NaN,1.987100e+13,NaN,NaN,6,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1988,2,1,NaN,1.987100e+13,NaN,NaN,34,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1988,3,1,NaN,1.986100e+13,NaN,NaN,17,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18242921,18242922,1997,60517,12,299.0424,1.997091e+13,NaN,NaN,56,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18242922,18242923,1997,60517,12,299.0424,1.997091e+13,NaN,NaN,56,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18242923,18242924,1997,60517,12,299.0424,1.997091e+13,NaN,NaN,56,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18242924,18242925,1997,60517,12,299.0424,1.997091e+13,NaN,NaN,56,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18242925,18242926,1997,60517,12,299.0424,1.997091e+13,NaN,NaN,56,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df = pd.set_index("STATEFIP")

AttributeError: module 'pandas' has no attribute 'set_index'

In [7]:
df = df.set_index("STATEFIP")

In [8]:
df

,Unnamed: 0,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,ASECWTH,PERNUM,WTFINL,...,OCC50LY,INDLY,OCC90LY,IND90LY,FULLPART,FIRMSIZE,INCTOT,INCWAGE,EDATT,EDATTLY
STATEFIP,,,,,,,,,,,,,,,,,,,,,
6,1,1988,1,1,NaN,1.987100e+13,NaN,NaN,1,2901.0600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2,1988,1,1,NaN,1.987100e+13,NaN,NaN,2,2877.9600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3,1988,1,1,NaN,1.987100e+13,NaN,NaN,3,3152.0400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,4,1988,2,1,NaN,1.987100e+13,NaN,NaN,1,1241.0400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,5,1988,3,1,NaN,1.986100e+13,NaN,NaN,1,1922.3700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,18242922,1997,60517,12,299.0424,1.997091e+13,NaN,NaN,2,299.0424,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,18242923,1997,60517,12,299.0424,1.997091e+13,NaN,NaN,3,231.2252,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,18242924,1997,60517,12,299.0424,1.997091e+13,NaN,NaN,4,210.2731,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,18242925,1997,60517,12,299.0424,1.997091e+13,NaN,NaN,5,308.4451,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,18242926,1997,60517,12,299.0424,1.997091e+13,NaN,NaN,6,210.2731,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
nj_df = df.loc[34]
nj_df

,Unnamed: 0,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,ASECWTH,PERNUM,WTFINL,...,OCC50LY,INDLY,OCC90LY,IND90LY,FULLPART,FIRMSIZE,INCTOT,INCWAGE,EDATT,EDATTLY
STATEFIP,,,,,,,,,,,,,,,,,,,,,
34,4,1988,2,1,NaN,1.987100e+13,NaN,NaN,1,1241.0400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,41,1988,23,1,NaN,1.987120e+13,NaN,NaN,1,1537.2900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,208,1988,92,1,NaN,1.988010e+13,NaN,NaN,1,1266.4100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,209,1988,92,1,NaN,1.988010e+13,NaN,NaN,2,1288.7100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,210,1988,92,1,NaN,1.988010e+13,NaN,NaN,3,1212.1600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34,18192014,1997,35151,12,1756.0738,1.997110e+13,NaN,NaN,2,1788.7814,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,18192015,1997,35153,12,1943.3435,1.997120e+13,NaN,NaN,1,1943.3435,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,18192016,1997,35153,12,1943.3435,1.997120e+13,NaN,NaN,2,1972.5741,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,18192017,1997,35153,12,1943.3435,1.997120e+13,NaN,NaN,3,2071.7033,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,18192018,1997,35153,12,1943.3435,1.997120e+13,NaN,NaN,4,3551.3006,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
pa_df = df.loc[42]
pa_df

,Unnamed: 0,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,ASECWTH,PERNUM,WTFINL,...,OCC50LY,INDLY,OCC90LY,IND90LY,FULLPART,FIRMSIZE,INCTOT,INCWAGE,EDATT,EDATTLY
STATEFIP,,,,,,,,,,,,,,,,,,,,,
42,40,1988,22,1,NaN,1.987120e+13,NaN,NaN,1,1924.5100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,47,1988,25,1,NaN,1.987110e+13,NaN,NaN,1,2111.1200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,48,1988,25,1,NaN,1.987110e+13,NaN,NaN,2,1966.4800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,52,1988,28,1,NaN,1.986120e+13,NaN,NaN,1,1883.3500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,53,1988,28,1,NaN,1.986120e+13,NaN,NaN,2,1902.0600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,18219318,1997,48979,12,1892.5032,1.997110e+13,NaN,NaN,2,1892.5032,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,18219319,1997,48980,12,2317.6384,1.997110e+13,NaN,NaN,1,2317.6384,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,18219320,1997,48980,12,2317.6384,1.997110e+13,NaN,NaN,2,2039.9635,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,18219321,1997,48980,12,2317.6384,1.997110e+13,NaN,NaN,3,2142.6876,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,18219322,1997,48981,12,2303.5165,1.997110e+13,NaN,NaN,1,2303.5165,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
pa_df_simp = pa_df[["YEAR", "MONTH", "EMPSTAT", "UHRSWORKT", "AGE", "SEX"]]
pa_df_simp

nj_df_simp = nj_df[["YEAR", "MONTH", "EMPSTAT", "UHRSWORKT", "AGE", "SEX"]]
nj_df_simp

          YEAR  MONTH  EMPSTAT  UHRSWORKT  AGE  SEX
STATEFIP
34        1988      1       34        NaN   73    2
34        1988      1       10        NaN   62    1
34        1988      1       10        NaN   33    1
34        1988      1       31        NaN   33    2
34        1988      1        0        NaN    9    1
...        ...    ...      ...        ...  ...  ...
34        1997     12       10       40.0   53    1
34        1997     12       10       40.0   46    1
34        1997     12       21      999.0   44    2
34        1997     12       34      999.0   17    1
34        1997     12       34      999.0   27    1

[717270 rows x 6 columns]

In [23]:
nj_df_simp.to_csv("nj_df_simp.csv")

In [24]:
pa_df_simp.to_csv("pa_df_simp.csv")